@host=http://localhost:5273

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstName": "Gabriel",
  "lastName": "Domingos",
  "email": "gabriel@email.com",
  "password": "password-hard"
}
