@host=http://localhost:5273

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmN2JiM2QwOS01ZDk1LTQxNzctYjZkYS01YjdiNjZlYThmN2MiLCJnaXZlbl9uYW1lIjoiR2FicmllbCIsImZhbWlseV9uYW1lIjoiRG9taW5nb3MiLCJqdGkiOiIzYzQ1NTRlMy0wMGYwLTQxMDAtYWI5Ny0zMjNjMzVkZDk3MmYiLCJleHAiOjE3Mzg4OTk2MjcsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.epMG_BkEs_HkktVWrvfb399yADNGvd4QPn9DxdNaXZE